#!/bin/bash

javac -client main/Main.java graphComponents/Graph.java graphComponents/Vertex.java graphUtils/General.java graphUtils/SimpleTuple.java graphUtils/SimpleQueuePrio.java matchingAlgs/Matching.java && java main.Main
